<?xml version="1.0"?>
<package format="2">
  <name>robot_remould</name>
  <version>0.1.0</version>
  <description>Custom launch files for Turtlebot3 Waffle indoor robot simulation</description>
  <maintainer email="user@todo.com">user</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>turtlebot3_description</exec_depend>
</package>
